### ISSUE TITLE
Misc fixes for calling

### ISSUE THREAD

**Issue by gabriel0003** [openline-ai/openline-customer-os#1157]
* though the dtmf dialpad needs to look like buttons
* for outbound calls, you should be showing the “to” instead of the “from” for “in call with”
* close dialog on hangup
* call transfer

**Comment by avalot** [comment]
- [ ] When the call is live, we should replace the four action buttons on the ID card with the relevant buttons for calling: 
- Hang Up (In red, in the place where the "call" button is normally) (perhaps use a delay to avoid double-clicks triggering call+hangup)
...then a bit of extra space, and...
- Mute
- Hold
- DTMF dialpad
- Transfer

- [ ] Look at the wireframes below for the transfer functionality. Note that because we are placing these buttons in the ID card (instead of in a floating panel), we don't need to indicate the contact name. It's obvious. 
( Figma: https://www.figma.com/file/mQIZRp3lFjvOFkLvNIq27E/Call-Transfer-for-Torrey?node-id=0%3A1&t=VSE0nqUZaPHKRuIp-1 )  

<img width="1016" alt="image" src="https://user-images.githubusercontent.com/831133/223191767-5112dea8-f7c2-4dcf-b5a6-8b8d08f10d3a.png">

**Comment by gabriel0003** [comment]
@avalot the current task was meant for things we can do until the demo. I would move the improvements you have to a different task
