### ISSUE TITLE
Animate expand/collapse of emails, and track location

### ISSUE THREAD

**Issue by avalot** [openline-ai/openline-customer-os#1177]
**Overview of the feature request and the problem you're looking to solve**
When I expand an email, the expansion should be animated (fast).

When I collapse an email, the collapse should also be animated, and my scrolling position in the timeline should go back to the top of the (now collapsed) email.

**Comment by Kasia9090** [comment]
@avalot this issue is blocked by new timeline query. 
Current timeline was hacked around to get and display data in desired format - that came at a cost of complex structure and a lot of hacks. 
There is no point of FE team loosing time on hacking around animation when we know that timeline will be drastically changed soon. For this reason I'm removing this task from "spaces launch" milestone

The main issue of user landing in unexpected place is the timeline was fixed in this issue https://github.com/openline-ai/openline-customer-os/issues/1221
