### ISSUE TITLE
Otto the otter not working well enough.

### ISSUE THREAD

**Issue by avalot** [openline-ai/openline-customer-os#1237]
Clicking on Otto brings up a chatbot. I can enter a question, but then:

- Clicking "Send" does nothing.
- Hitting enter clears the input box, but nothing appears in the chat.

I'm on Safari ( https://gs.statcounter.com/browser-market-share )

**Comment by Kasia9090** [comment]
### Findings:
**The bug is not connected to specific browser!!!**
- web chat works on our website
- webchat doesn't work on spaces

**root cause:**
- invalid request url / lack of related env variables for prod env 

TODO:
- [x] Add env variables
- [x] Check if everything is working after next deployment
